### ISSUE TITLE
bsm gamma calc typo

### ISSUE THREAD

**Issue by mbalkanloo** [psaris/qtips#2]
https://github.com/psaris/qtips/blob/0108efaae60907b9afa3ee90c5fa0c424d30053a/deriv.q#L42

should this lower case "s" (sigma) be capital "S" (spot)?

**Comment by mbalkanloo** [comment]
i also wonder if the numerator should be changed to the standard normal PDF. if i am not mistaken, the current implementation is using the CDF.

the use of the CDF where the PDF is in order might also affect the vega and theta calcs.

also, does vega have an additional sigma factor introduced by the `ssrt` var?

**Comment by mbalkanloo** [comment]
i am closing this issue because i am sure that it is not relevant to the book's fundamental purpose. i was looking for a Black Scholes implementation in q and this one provides an excellent starting point. thank you.

**Comment by psaris** [comment]
thank you @mbalkanloo!  confusing how this escaped detection.  will post a fix for this.

**Comment by psaris** [comment]
> i am closing this issue because i am sure that it is not relevant to the book's fundamental purpose. i was looking for a Black Scholes implementation in q and this one provides an excellent starting point. thank you.

@mbalkanloo, just pushed a fix for the calculation, and although i'd prefer to refactor the normal pdf function into ``.stat.npdf``, i'll save that until Q Tips 2.0.
