### ISSUE TITLE
Errata for ch6 - fills

### ISSUE THREAD

**Issue by sshanks-kx** [psaris/qtips#3]
Noticed on page65 that 'fills' is defined as 'each element is filled with the prior value' - missing mention of nulls ( https://code.kx.com/q/ref/fill/#fills )

https://github.com/psaris/qtips/blob/master/errata.adoc#chapter-6-a-random-walk

Thanks

**Comment by psaris** [comment]
thank you @sshanks-kx! i've updated the errata to indicate that the text should read: "Each value null value element is replaced with the last prior non-null value".

note that the fills operator is explained again on page 125 and is accompanied by the following text "The fills operator fills forward the last non-null value."
