### ISSUE TITLE
Question for Chapter 3

### ISSUE THREAD

**Issue by 85-hub** [psaris/qtips#4]
On page 32, there are scripts as below:

q) system "S ", string 1+"i"$.z.T
q) \S

Why is there whitespace after the system variable S?

**Comment by psaris** [comment]
hello @85-hub,

the `\S` system command sets the rng seed.  it is followed by a space and then an integer.  to set the value to 10, we would type:

```q
\S 10
```
system commands that are not defined in q are assumed to be commands defined by the operating system. not including the white space would result in a non-existent os command:

```q
q)\S10
sh: S10: command not found
'os
  [0]  \S10
       ^
```
the second line of your question requests the current value of the rng seed:
```q
q)\S
10i
```
the value in the book should display the following:
```q
q)\S
55538672
```
does it?
